# Generated by Django 5.0.7 on 2024-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urban", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="sentence",
            field=models.CharField(blank="True", max_length=1000, null="True"),
            preserve_default="True",
        ),
    ]
